### ISSUE TITLE
Checkstyle configuration Idea (help)

### ISSUE THREAD

**Issue by kissdave** [BSStudio/WebCentral-Backend#1]
Hi!

I am trying to configure the checkstyle in IntelliJ IDEA. I followed the instructions in the readme, but I have other options to choose from at import.

![image](https://user-images.githubusercontent.com/15999510/50368233-a98f2d00-0586-11e9-88d3-d80da49cb34b.png)

If I try to import as an _IntelliJ IDEA code style XML_ I get the following error:

![image](https://user-images.githubusercontent.com/15999510/50368250-e9eeab00-0586-11e9-905e-1da0fcbbceb7.png)

I use IntelliJ verion: IntelliJ IDEA 2018.3 (Ultimate Edition) _(Build #IU-183.4284.148, built on November 21, 2018)_

What am I doing wrong?

**Comment by veresspeter** [comment]
Hi!

You need to install Checkstyle plugin first.
I'll update the readme with this.
